### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by nicholaides** [picwell/schematics-extensions#5]
Each class should have some documentation on its use. ATM, that's:

- [x] `ImmutableModel`
- [x] `MockableListType`
- [x] `MockableModelType`
- [x] `NumericStringType`

**Comment by nicholaides** [comment]
Anybody have a good idea of how to generate documentation from that? Should we just put it in the README instead of in docstrings?

**Comment by csojinb-picwell** [comment]
Docstrings seem good. There seem to be a fair number of tools for auto-generating documentation from docstrings, but I've not used any of them
